lib/javsalynn_smanager_web/router.ex
defmodule JavsalynnSmanagerWeb.Router do
  use JavsalynnSmanagerWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end


  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :frontend  do
    plug JavsalynnSmanagerWeb.Plugs.LoadUser
    
  end

  scope "/", JavsalynnSmanagerWeb do
    pipe_through :browser

    
    get "/login", SessionController, :new
    post "/login", SessionController, :create
    get "/register", RegistrationController, :new
    post "/register", RegistrationController, :create
   
    
  end
  scope "/", JavsalynnSmanagerWeb do
    pipe_through [:browser, :frontend, JavsalynnSmanagerWeb.Plugs.AuthUser]

    get "/", PageController, :index
    get "/logout", SessionController, :delete
    
  end
  # Other scopes may use custom stacks.
  # scope "/api", JavsalynnSmanagerWeb do
  #   pipe_through :api
  # end
end

lib/javsalynn_smanager/account/account.ex
defmodule JavsalynnSmanager.Account do
  alias JavsalynnSmanager.Repo
  alias JavsalynnSmanager.Account.User

  def get_user!(id), do: Repo.get!(User, id)

  def list_users do
    Repo.all(Users)
  end

  def build_user(attrs \\ %{}) do
    %User{}
    |> User.changeset(attrs)
  end

  def change_user(%User{} = user, attrs \\ %{}) do
    user
    |> User.changeset( attrs)
  end

  def create_user(attrs) do
    attrs
    |> build_user
    |> Repo.insert
  end

  def get_user!(id) do
      Repo.get!(User, id)
      |> Repo.preload(:user)
  end

  def get_user_by_email(email), do: Repo.get_by(User, email: email)

  def get_user_by_credentials(%{"email" => email, "password" => pass} ) do
    user = get_user_by_email(email)
    cond do
      user && Bcrypt.verify_pass(pass, user.encrypted_password) ->
        user
      true ->
        :error
    end
  end
end

lib/javsalynn_smanager/account/user.ex
defmodule JavsalynnSmanager.Account.User do
  use Ecto.Schema
  import Ecto.Changeset

  alias JavsalynnSmanager.Account.User

  schema "users" do
    field :email,                 :string
    field :encrypted_password,    :string
    field :firstname,             :string
    field :lastname,              :string
    field :phone,                 :string
    field :password,              :string, virtual: true
    field :password_confirmation, :string, virtual: true

    timestamps()
  end

  @doc false
  def changeset(%User{} = user, attrs) do
    user
    |> cast(attrs, [:firstname, :lastname, :email, :password_confirmation, :password, :phone])
    |> validate_required([:firstname, :lastname, :phone, :email,   :password, :password_confirmation])
    |> validate_format(:email, ~r/@/, message: "is invalid")
    |> validate_length(:password, min: 6, max: 100)
    |> validate_confirmation(:password, message: "does not match password")
    |> unique_constraint(:email)
    |> put_encrypted_password
  end

  defp put_encrypted_password(changeset) do
    case changeset.valid? do
      true ->
        changes = changeset.changes
        put_change(changeset, :encrypted_password,  Bcrypt.hash_pwd_salt(changes.password))
      _ ->
        changeset
    end
  end
end

lib/javsalynn_smanager/application.ex
defmodule JavsalynnSmanager.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    # List all child processes to be supervised
    children = [
      # Start the Ecto repository
      JavsalynnSmanager.Repo,
      # Start the endpoint when the application starts
      JavsalynnSmanagerWeb.Endpoint
      # Starts a worker by calling: JavsalynnSmanager.Worker.start_link(arg)
      # {JavsalynnSmanager.Worker, arg},
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: JavsalynnSmanager.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    JavsalynnSmanagerWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/javsalynn_smanager/repo.ex
defmodule JavsalynnSmanager.Repo do
  use Ecto.Repo,
    otp_app: :javsalynn_smanager,
    adapter: Ecto.Adapters.Postgres
end

lib/javsalynn_smanager_web/controllers/page_controller.ex
defmodule JavsalynnSmanagerWeb.PageController do
  use JavsalynnSmanagerWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end
end

lib/javsalynn_smanager_web/controllers/registration_controller.ex
defmodule JavsalynnSmanagerWeb.RegistrationController do
  use JavsalynnSmanagerWeb, :controller
  alias JavsalynnSmanager.Account
  alias JavsalynnSmanager.Account.User

  

  def new(conn, _) do
    changeset = Account.change_user(%User{})
    render(conn, "new.html", changeset: changeset)
  end
  

  def create(conn, %{"registration" => registration_params}) do
    case Account.create_user(registration_params) do
      {:ok, _user} ->
        conn
        |> put_flash(:info, "Registration successful")
        |> redirect(to: Routes.page_path(conn, :index))
      {:error, changeset} ->
      changeset|> IO.inspect
        conn
        |> render(:new, changeset: changeset)
    end
  end
end

lib/javsalynn_smanager_web/controllers/session_controller.ex
defmodule JavsalynnSmanagerWeb.SessionController do
  use JavsalynnSmanagerWeb, :controller
  alias JavsalynnSmanager.Account

  def new(conn, _params) do
    render(conn, "new.html")
  end

  def create(conn, %{"session" => session_params}) do
    case Account.get_user_by_credentials(session_params) do
      :error ->
        conn
        |> put_flash(:error, "Invalid username/password combination")
        |> render("new.html")
      user ->
        path = get_session(conn, :intending_to_visit) || Routes.page_path(conn, :index)
        conn
        |> assign(:current_user, user)
        |> put_session(:user_id, user.id)
        |> configure_session(renew: true)
        |> put_flash(:info, "Login successful")
        |> redirect(to: path)
    end
  end

  def delete(conn, _) do
   clear_session(conn)
   |> put_flash(:info, "You have been logged out")
   |> redirect(to: Routes.page_path(conn, :index))
  end
end

lib/javsalynn_smanager_web/views/error_view.ex
defmodule JavsalynnSmanagerWeb.ErrorView do
  use JavsalynnSmanagerWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/javsalynn_smanager_web/views/layout_view.ex
defmodule JavsalynnSmanagerWeb.LayoutView do
  use JavsalynnSmanagerWeb, :view
end

lib/javsalynn_smanager_web/views/page_view.ex
defmodule JavsalynnSmanagerWeb.PageView do
  use JavsalynnSmanagerWeb, :view
end

lib/javsalynn_smanager_web/views/registration_view.ex
defmodule JavsalynnSmanagerWeb.RegistrationView do
  use JavsalynnSmanagerWeb, :view
end

lib/javsalynn_smanager_web/views/session_view.ex
defmodule JavsalynnSmanagerWeb.SessionView do
  use JavsalynnSmanagerWeb, :view
end

lib/javsalynn_smanager_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>JavSalynn Foundation</title>

    <!-- Browser Tab Icon
	<link rel="icon" href="img/favicon.jpg"> -->

    <!-- Bootstrap core CSS -->


    <!-- Font Link -->
    <link href='https://fonts.googleapis.com/css?family=Rubik' rel='stylesheet'>

<link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>



</head>

      <%= render @view_module, @view_template, assigns %>






          <script src="<%= Routes.static_path(@conn, "/vendor/") %>jquery.js"></script>
          <script src="<%= Routes.static_path(@conn, "/") %>vendor/bootstrap/js/bootstrap.min.js"></script>
          <script src="<%= Routes.static_path(@conn, "/") %>vendor/owlcarousel/owl.carousel.js"></script>
      	<script src="<%= Routes.static_path(@conn, "/") %>js/scripts.js"></script>

      </body>

      </html>
</html>

lib/javsalynn_smanager_web/templates/page/index.html.eex
<section class="phx-hero">
  <h1><%= gettext "Welcome to %{name}!", name: "Phoenix" %></h1>
  <p>A productive web framework that<br/>does not compromise speed and maintainability.</p>
</section>

<section class="row">
  <article class="column">
    <h2>Resources</h2>
    <ul>
      <li>
        <a href="https://hexdocs.pm/phoenix/overview.html">Guides &amp; Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix/blob/v1.4/CHANGELOG.md">v1.4 Changelog</a>
      </li>
    </ul>
  </article>
  <article class="column">
    <h2>Help</h2>
    <ul>
      <li>
        <a href="https://elixirforum.com/c/phoenix-forum">Forum</a>
      </li>
      <li>
        <a href="https://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on Freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">Twitter @elixirphoenix</a>
      </li>
    </ul>
  </article>
</section>

lib/javsalynn_smanager_web/templates/session/new.html.eex
<body>
    <section class="auth-section d-flex justify-content-center py-3 align-items-center">

        <div class="auth-layer px-3 py-5">

                <%= form_for @conn, Routes.session_path(@conn, :create), [as: :session,class: "d-flex h-100 justify-content-center align-items-center flex-column", id: "session-form"], fn f -> %>
                <header class="text-center font-weight-bold mb-5">
                    Signin
                </header>


                <div class="form-group my-3 w-100">

                     <%= text_input f, :email, placeholder: "Email Address", class: "form-control custom-auth-input px-4" %>
                </div>
                <div class="form-group my-3 w-100">

                    <%= password_input f, :password, placeholder: "Password", class: "form-control custom-auth-input px-4" %>
                </div>
                <button class="btn custom-btn smaller-btn mt-2 btn-block py-2">SIGNIN </button>
            <% end %>
            <div class="mt-5 pt-5">
                            <p class="text-center auth-link">
                                Dont Have an account? <a href="<%= Routes.registration_path(@conn,:new)%>">sign up now</a>
                            </p>
                        </div>
        </div>

    </section>